service: candlestick-events-service 

provider:
  name: aws
  runtime: python3.7
  profile: loidsig
  region: us-east-1
  stage: prod
  memorySize: 256

package:
  include:
    - binance_candlestick_events.py
    - candlestick_features.py
  exclude:
    - requirements.txt
    - serverless.yml
    - package.json
    - package-lock.json
    - node_modules/**

functions:         
  binance-candlestick-events:
    role: arn:aws:iam::309597787617:role/lambda_basic_execution
    handler: binance_candlestick_events.main
    events:
      - schedule:
          name: binance-candlestick-scheduler
          description: 'binance raw events schedule'
          rate: rate(1 minute)
          enabled: true
    onError: arn:aws:sns:us-east-1:309597787617:candlestick_pipeline_notifications
    timeout: 60
  candlestick-features:
    role: arn:aws:iam::309597787617:role/lambda_basic_execution
    handler: candlestick_features.main
    #reservedConcurrency: 400
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:309597787617:candlestick_events
          batchSize: 1
    onError: arn:aws:sns:us-east-1:309597787617:candlestick_pipeline_notifications
    timeout: 60

plugins:
  - serverless-python-requirements

custom:   
  pythonRequirements:
    dockerizePip: true
